controller_list:
    - name: robot/joint_gr
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - motortom2m
      - joint2
      - joint4
      - joint6

    - name: robot/end_gr
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
      - end
